// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDriNMBEjDnax_PREalzENpzBjag9lxc_s',
    appId: '1:326621224329:web:afbe4309f9d4d99fb99558',
    messagingSenderId: '326621224329',
    projectId: 'chat-573b4',
    authDomain: 'chat-573b4.firebaseapp.com',
    databaseURL: 'https://chat-573b4-default-rtdb.firebaseio.com',
    storageBucket: 'chat-573b4.appspot.com',
    measurementId: 'G-X8CEBFWE42',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBpsvTKt7sF7Fatcjg8KbIRZQ-ERAaLmVA',
    appId: '1:326621224329:android:f1c140ecc3d4f92bb99558',
    messagingSenderId: '326621224329',
    projectId: 'chat-573b4',
    databaseURL: 'https://chat-573b4-default-rtdb.firebaseio.com',
    storageBucket: 'chat-573b4.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAlAiFpjBZxXYKFGatE0HnO9n0Wz2oWxXg',
    appId: '1:326621224329:ios:1da9170f2b4e29dcb99558',
    messagingSenderId: '326621224329',
    projectId: 'chat-573b4',
    databaseURL: 'https://chat-573b4-default-rtdb.firebaseio.com',
    storageBucket: 'chat-573b4.appspot.com',
    iosClientId:
        '326621224329-kfjqhnp278htiehdsumn2g5dcppf4tip.apps.googleusercontent.com',
    iosBundleId: 'com.example.chat',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAlAiFpjBZxXYKFGatE0HnO9n0Wz2oWxXg',
    appId: '1:326621224329:ios:1da9170f2b4e29dcb99558',
    messagingSenderId: '326621224329',
    projectId: 'chat-573b4',
    databaseURL: 'https://chat-573b4-default-rtdb.firebaseio.com',
    storageBucket: 'chat-573b4.appspot.com',
    iosClientId:
        '326621224329-kfjqhnp278htiehdsumn2g5dcppf4tip.apps.googleusercontent.com',
    iosBundleId: 'com.example.chat',
  );
}
